import { Link } from 'react-router-dom';
import { ArrowUpRight, BarChart3, ChevronRight, CircleAlert, Cpu, Database, GitCompareArrows, Plus, Radar, ShieldCheck, Sparkles, Target, Timer, TrendingUp, Zap } from 'lucide-react';

const factors = [
  ['vol_rank_decay_042', 'LLM → GP', '.061', '1.42', '.054', '18.3%', '.34', 'OOS PASS'],
  ['oi_price_div_017', 'GP', '.057', '1.21', '.028', '22.1%', '.81', 'REVIEW'],
  ['funding_mean_rev', 'RL', '.049', '1.37', '.047', '11.4%', '.22', 'STABLE'],
  ['vol_momentum_031', 'GP', '.046', '1.18', '.039', '15.8%', '.41', 'REVIEW'],
  ['long_short_bias_009', 'LLM', '.043', '1.08', '.031', '9.7%', '.18', 'NEW'],
];
const funnel = [['Generated','18,420','cyan'],['Valid','9,831','blue'],['IC Pass','1,284','indigo'],['Stable','437','violet'],['Corr Dedup','92','amber'],['OOS Pass','34','green'],['Accepted','8','emerald']];

export function Home() {
  return <div className="overview-page">
    <div className="page-heading"><div><div className="eyebrow"><Radar size={13}/> RESEARCH COMMAND CENTER</div><h1>Overview</h1><p>Track the complete factor research funnel across your active workspace.</p></div><div className="heading-actions"><button className="button-secondary"><Timer size={14}/> Last 7 days <ChevronRight size={13}/></button><Link to="/launchpad" className="button-primary"><Plus size={15}/> New research</Link></div></div>

    <section className="funnel-panel panel"><div className="panel-heading"><div><span className="eyebrow">RESEARCH FUNNEL</span><h2>Candidate lifecycle</h2></div><span className="muted-label">Updated 09:42 UTC <span className="status-dot" /></span></div><div className="funnel-row">{funnel.map(([label, value, color], index) => <div className="funnel-step" key={label}><div className={`funnel-number ${color}`}>{value}</div><div className="funnel-label">{label}</div>{index < funnel.length - 1 && <ChevronRight className="funnel-arrow" size={14}/>}</div>)}</div></section>

    <div className="overview-grid top-grid"><section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">TOP NEW FACTORS</span><h2>Highest signal quality</h2></div><Link to="/inspector" className="text-link">Open library <ArrowUpRight size={13}/></Link></div><div className="table-wrap"><table><thead><tr>{['Factor','Miner','RankIC','ICIR','OOS IC','Turnover','Max Corr','Status'].map((head) => <th key={head}>{head}</th>)}</tr></thead><tbody>{factors.map((factor) => <tr key={factor[0]}><td><Link to={`/inspector?factor=${factor[0]}`} className="factor-link">{factor[0]}</Link><span className="table-sub">cross-sectional expression</span></td>{factor.slice(1).map((cell, index) => <td key={`${factor[0]}-${index}`} className={index === 6 ? `status-cell ${cell === 'OOS PASS' ? 'pass' : cell === 'STABLE' ? 'stable' : cell === 'NEW' ? 'new' : 'review'}` : 'mono'}>{cell}</td>)}</tr>)}</tbody></table></div></section>
      <section className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">ACTIVE EXPERIMENTS</span><h2>Compute queue</h2></div><Link to="/launchpad" className="text-link">View all <ArrowUpRight size={13}/></Link></div><div className="experiment-list">{[['GP Mining #184','78%','Generation 31 / 40','cyan'],['LLM Mining #185','54%','Candidate 81 / 150','violet'],['RL Search #186','31%','Episode 124 / 400','amber']].map(([name, progress, detail, color]) => <div className="experiment" key={name}><div className="experiment-top"><b>{name}</b><span className="mono">{progress}</span></div><div className="progress-track"><span className={color} style={{width: progress}} /></div><div className="experiment-bottom"><span>{detail}</span><span>Running</span></div></div>)}</div><Link to="/launchpad" className="panel-footer-link">Open mining workspace <ChevronRight size={14}/></Link></section></div>

    <div className="overview-grid bottom-grid"><section className="panel metrics-panel"><div className="panel-heading"><div><span className="eyebrow">RESEARCH ACTIVITY</span><h2>Session telemetry</h2></div><Zap size={16} className="accent-icon"/></div><div className="telemetry-grid">{[['Candidates today','2,481',TrendingUp,'+18.4%'],['Accepted factors','8',ShieldCheck,'+3 this week'],['Best OOS RankIC','.054',Target,'vol_rank_decay'],['Failed tasks','2',CircleAlert,'-40% vs last week']].map(([label,value,Icon,note]) => { const MetricIcon = Icon as typeof TrendingUp; return <div className="telemetry-item" key={label as string}><MetricIcon size={14}/><span>{label as string}</span><b>{value as string}</b><small>{note as string}</small></div> })}</div><div className="resource-strip"><span><Cpu size={13}/> CPU <b>22%</b></span><span><Database size={13}/> Storage <b>68%</b></span><span><BarChart3 size={13}/> Memory <b>41%</b></span></div></section><section className="panel session-panel"><div className="panel-heading"><div><span className="eyebrow">CURRENT SESSION</span><h2>Research environment</h2></div><Sparkles size={16} className="accent-icon"/></div><div className="session-list"><div><span>Universe</span><b>Crypto Top50</b></div><div><span>Timeframe</span><b>1H · Forward +4H</b></div><div><span>Dataset</span><b>Crypto_Perpetual_1H_v12</b></div><div><span>Validation</span><b className="green-text">Train / Val / OOS active</b></div></div><button className="compare-button"><GitCompareArrows size={14}/> Compare selected factors</button></section></div>
  </div>;
}
