import { Link } from 'react-router-dom';
import { ArrowUpRight, ChevronRight, CircleAlert, Plus, Radar, ShieldCheck, Timer, TrendingUp, Workflow } from 'lucide-react';
import { projects, experiments, researchActivity, runs } from '../data/researchData';

const Metric = ({ label, value, note }: { label: string; value: string; note: string }) => <div className="workspace-metric"><span>{label}</span><b>{value}</b><small>{note}</small></div>;
const Status = ({ children }: { children: string }) => <span className={`status-pill status-${children.toLowerCase()}`}>{children}</span>;

export function Home() {
  return <div className="overview-page">
    <div className="page-heading"><div><div className="eyebrow"><Radar size={13}/> WORKSPACE / OVERVIEW</div><h1>Workspace Overview</h1><p>Factor research workspace activity, projects and reproducible runs.</p></div><div className="heading-actions"><button className="button-secondary"><Timer size={14}/> Last 7 days <ChevronRight size={13}/></button><Link to="/idea" className="button-primary"><Plus size={15}/> New research</Link></div></div>
    <div className="workspace-metrics"><Metric label="Active Projects" value="2" note="of 3 projects"/><Metric label="Experiments" value="8" note="2 running"/><Metric label="Running Runs" value="3" note="18,420 candidates"/><Metric label="Total Factors" value="48" note="11 validated"/><Metric label="Promoted Factors" value="8" note="+2 this week"/></div>
    <section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">WORKSPACE / PROJECTS</span><h2>Active research projects</h2></div><Link to="/projects" className="text-link">View all <ArrowUpRight size={13}/></Link></div><div className="table-wrap"><table><thead><tr><th>Project</th><th>Research goal</th><th>Default dataset</th><th>Universe</th><th>Timeframe</th><th>Experiments</th><th>Runs</th><th>Factors</th><th>Status</th></tr></thead><tbody>{projects.map(project => <tr key={project.id}><td><Link className="factor-link" to={`/projects/${project.id}`}>{project.name}</Link><span className="table-sub">{project.id}</span></td><td>{project.researchGoal}</td><td className="mono">{project.defaultDataset}</td><td className="mono">{project.defaultUniverse}</td><td className="mono">{project.defaultTimeframe}</td><td className="mono">{project.experiments}</td><td className="mono">{project.runs}</td><td className="mono">{project.factors} <small>({project.promoted} promoted)</small></td><td><Status>{project.status}</Status></td></tr>)}</tbody></table></div></section>
    <div className="overview-grid top-grid"><section className="panel table-panel"><div className="panel-heading"><div><span className="eyebrow">RECENT EXPERIMENTS</span><h2>Research designs</h2></div><Link to="/experiments" className="text-link">Open experiments <ArrowUpRight size={13}/></Link></div><div className="table-wrap"><table><thead><tr><th>Experiment</th><th>Project</th><th>Miner</th><th>Latest run</th><th>Factors</th><th>Status</th></tr></thead><tbody>{experiments.map(experiment => <tr key={experiment.id}><td><Link className="factor-link" to={`/experiments/${experiment.id}`}>{experiment.name}</Link><span className="table-sub">{experiment.id}</span></td><td>Crypto Short-term Alpha</td><td className="mono">{experiment.miner}</td><td className="mono">{experiment.progress}%</td><td className="mono">{experiment.accepted}</td><td><Status>{experiment.status === '运行中' ? 'Running' : experiment.status === '已完成' ? 'Completed' : 'Failed'}</Status></td></tr>)}</tbody></table></div></section><section className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">RUNNING RUNS</span><h2>Compute activity</h2></div><Link to="/runs" className="text-link">View all <ArrowUpRight size={13}/></Link></div><div className="experiment-list">{runs.filter(run => run.status === 'Running').map(run => <div className="experiment" key={run.id}><div className="experiment-top"><Link to={`/runs/${run.id}`}><b>{run.id}</b></Link><span className="mono">{run.progress}%</span></div><div className="progress-track"><span className="cyan" style={{ width: `${run.progress}%` }}/></div><div className="experiment-bottom"><span>{run.stage}</span><span>{run.compute}</span></div></div>)}</div><Link to="/tasks" className="panel-footer-link">Open task center <ChevronRight size={14}/></Link></section></div>
    <section className="panel activity-feed"><div className="panel-heading"><div><span className="eyebrow">RECENT RESEARCH ACTIVITY</span><h2>Workspace timeline</h2></div><Workflow size={16} className="accent-icon"/></div>{researchActivity.map(([event, target, time]) => <div className="activity-row" key={`${event}-${target}`}><span className="activity-icon">{event === 'factor promoted' ? <ShieldCheck size={14}/> : event === 'run completed' ? <TrendingUp size={14}/> : <CircleAlert size={14}/>}</span><span><b>{event}</b><small>{target}</small></span><time>{time}</time></div>)}</section>
  </div>;
}
