import { useMemo, useState } from 'react';
import { Check, ChevronDown, GitCompareArrows, Play, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { Link } from 'react-router-dom';

const factors = [
  ['vol_rank_decay_042','GP','.061','1.42','.054','18.3%','.34','PROMOTED'],
  ['oi_price_div_017','GP','.057','1.21','.028','22.1%','.81','INSPECTED'],
  ['funding_mean_rev','RL','.049','1.37','.047','11.4%','.22','PROMOTED'],
  ['vol_momentum_031','GP','.046','1.18','.039','15.8%','.41','DISCOVERED'],
  ['long_short_bias_009','LLM','.043','1.08','.031','9.7%','.18','INSPECTED'],
  ['trade_imbalance_113','NN','.039','.96','.027','14.2%','.28','REJECTED'],
];
const features = ['OHLCV','Open Interest','Funding Rate','Trade Imbalance','Realized Volatility'];

export function Mining() {
  const [miner, setMiner] = useState('GP'); const [advanced, setAdvanced] = useState(false); const [run, setRun] = useState(false); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(features);
  return <div className="research-page mining-page"><PageTitle eyebrow="RESEARCH / MINING" title="Mining Experiment" description="Configure a reproducible factor search against the active research context." />
    <div className="mode-tabs"><button className={!advanced?'selected':''} onClick={()=>setAdvanced(false)}>Standard Mode</button><button className={advanced?'selected':''} onClick={()=>setAdvanced(true)}>Advanced Mode</button></div>
    <div className="mining-grid"><section className="panel form-panel"><div className="form-section"><span className="form-label">MINER TYPE</span><div className="segmented">{['GP','RL','LLM','NN'].map(item=><button key={item} className={miner===item?'selected':''} onClick={()=>setMiner(item)}>{item}</button>)}</div></div><div className="field-grid">{[['Universe','Crypto Top50'],['Timeframe','1H'],['Target','Forward Return +4H'],['Train Period','2022.01 — 2024.12'],['Validation Period','2025.01 — 2025.06'],['Test / OOS Period','2025.07 — 2026.08']].map(([label,value])=><label key={label}><span>{label}</span><select defaultValue={value}><option>{value}</option><option>Custom period</option></select></label>)}</div><div className="form-section"><div className="section-title"><span className="form-label">FEATURES</span><span className="muted-label">{selected.length} selected</span></div><div className="search-field"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search features"/></div><div className="feature-list">{features.filter(f=>f.toLowerCase().includes(query.toLowerCase())).map(feature=><button key={feature} className={selected.includes(feature)?'checked':''} onClick={()=>setSelected(s=>s.includes(feature)?s.filter(x=>x!==feature):[...s,feature])}>{selected.includes(feature)?<Check size={13}/>:<span className="empty-check"/>}{feature}</button>)}</div></div><div className="form-section"><div className="section-title"><span className="form-label">OPERATORS</span><button className="text-link">Select all</button></div><div className="operator-groups">{['Arithmetic','Time Series','Cross Sectional','Statistical','Custom'].map((group,i)=><button key={group} className={i<2?'active':''}>{group}<ChevronDown size={13}/></button>)}</div></div><div className="form-section"><div className="section-title"><span className="form-label">FITNESS WEIGHTS</span><button className="text-link"><Plus size={13}/> Add Metric</button></div>{[['RankIC','35%'],['ICIR','25%'],['Stability','20%'],['Turnover','-10%'],['Correlation','-10%']].map(([label,value])=><div className="weight-row" key={label}><span>{label}</span><input type="range" defaultValue={parseInt(value)} min="-20" max="50"/><b>{value}</b></div>)}</div></section>
      <aside className="panel preview-panel"><div className="panel-heading"><div><span className="eyebrow">EXPERIMENT PREVIEW</span><h2>Run configuration</h2></div><span className="status-dot"/></div><div className="preview-list">{[['Miner',miner],['Universe','Crypto Top50'],['Assets Count','83'],['Timeframe','1H'],['Target','Forward Return +4H'],['Search Space','17 features · 24 ops'],['Estimated Candidates','18,420'],['Validation Method','Purged walk-forward'],['Data Coverage','99.7%']].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="warning-list"><span className="form-label">WARNINGS</span><p className="warning">Correlation dedup disabled</p><p className="ok">OOS configured</p><p className="ok">Data coverage above 99%</p></div><div className="preview-actions"><button className="button-secondary">Save Config</button><button className="button-primary" onClick={()=>setRun(true)}><Play size={13}/>{run?'Mining queued':'Run Mining'}</button></div></aside></div></div>
}

export function Library() { const [search,setSearch]=useState(''); const [selected,setSelected]=useState<string[]>([]); const filtered=useMemo(()=>factors.filter(f=>f[0].includes(search.toLowerCase())),[search]); return <div className="research-page"><PageTitle eyebrow="FACTORS / LIBRARY" title="Factor Library" description="Browse, filter, and compare persisted research candidates." /><div className="library-toolbar"><div className="search-field"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search factors"/></div>{['Miner: All','Status: All','Source: All','Dataset: Active'].map(x=><button className="filter-button" key={x}>{x}<ChevronDown size={13}/></button>)}<span className="toolbar-spacer"/><button className="button-secondary" disabled={!selected.length}><GitCompareArrows size={14}/> Compare {selected.length||''}</button><button className="button-secondary">Export</button></div><div className="panel table-panel library-table"><table><thead><tr>{['','Factor','Miner','IC','RankIC','ICIR','OOS','Turnover','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(f=><tr key={f[0]}><td><input type="checkbox" checked={selected.includes(f[0])} onChange={()=>setSelected(s=>s.includes(f[0])?s.filter(x=>x!==f[0]):[...s,f[0]])}/></td><td><Link className="factor-link" to={`/inspector?factor=${f[0]}`}>{f[0]}</Link></td>{f.slice(1,7).map((x,i)=><td className="mono" key={i}>{x}</td>)}<td><span className={`status-pill ${f[7].toLowerCase()}`}>{f[7]}</span></td></tr>)}</tbody></table></div></div> }

function PageTitle({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><button className="icon-button"><SlidersHorizontal size={15}/> View options</button></div>}
